name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: jojotrujillo/pyinstaller-action-linux@dev
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: in-office-light
        path: dist
